### ISSUE TITLE
add checkboxes for noreferrer and nofollow

### ISSUE THREAD

**Issue by dws122** [maithemewp/mai-post-previews#1]
right now noreferrer is set, and typically I'd want that unset so that the target domain gets notified that we referred the traffic.

would like to have checkboxes on the block to enable these, with the default of no check for noreferrer and check for nofollow

**Comment by JiveDig** [comment]
@dws122 Adding checkboxes for:

- `noreferrer`
- `nofollow`

But what about:
- `noopener`
- `sponsored`
?

**Comment by JiveDig** [comment]
This is added via https://github.com/maithemewp/mai-post-previews/commit/1f5747ca38121f6ae60820cf74f117329cf63fdf

**Comment by JiveDig** [comment]
<img width="324" alt="CleanShot 2024-02-13 at 23 29 57@2x" src="https://github.com/maithemewp/mai-post-previews/assets/540990/0dc2190b-ee7b-4a04-ac9e-afebc66c135d">
